[10.0] [ADD] analytic_plan_mass_create
ForgeFlow/project-bid pull request #6
Opened 2017-09-22 08:52 UTC by nikul-serpentcs

migrated analytic_plan_mass_create module v10

@aheficent

2017-09-22 11:50 UTC, AaronHForgeFlow requested changes

2017-09-22 11:50 UTC, aheficent commented on analytic_plan_mass_create/wizard/analytic_plan_mass_create.py
> +        line_ids[0].on_change_amount_currency()
Got an error here when trying to create the planning lines

![image](https://user-images.githubusercontent.com/19620251/30743230-084db72c-9f9d-11e7-9cdc-4a824720f562.png)

2017-09-22 12:27 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-09-26 12:12 UTC, AaronHForgeFlow approved these changes
Just one minor comment.

2017-09-26 12:12 UTC, aheficent commented on analytic_plan_mass_create/static/description/index.html
>          <div class="oe_span6">
I think this file can be removed, create a readme instead.

2017-09-27 05:27 UTC, nikul-serpentcs commented
@aheficent Could you please look it.

2017-09-27 07:34 UTC, AaronHForgeFlow approved these changes
:+1: thanks for attending the comments. Can you squash the commits please?

2017-09-27 07:39 UTC, nikul-serpentcs commented
@aheficent Done squashed all commits.

2017-09-27 07:55 UTC, merged